const tempPizzaData = [
  {
    id: 1,
    price: '250.00',
    imageUrl: "https://via.placeholder.com/50",
    name: "Margherita",
    type: "Veg",
    size: "Large",
    base: "Thin",
    stage: "Order Placed",
    timeSpent: "5 min",
  },
  {
    id: 2,
    price: '250.00',
    imageUrl: "https://via.placeholder.com/50",
    name: "Pepperoni",
    type: "Non-Veg",
    size: "Medium",
    base: "Thick",
    stage: "Order In Making",
    timeSpent: "2 min",
  },
  {
    id: 3,
    price: '250.00',
    imageUrl: "https://via.placeholder.com/50",
    name: "Vegetarian",
    type: "Veg",
    size: "Small",
    base: "Thin",
    stage: "Order Ready",
    timeSpent: "10 min",
  },
  {
    id: 4,
    price: '250.00',
    imageUrl: "https://via.placeholder.com/50",
    name: "BBQ Chicken",
    type: "Non-Veg",
    size: "Large",
    base: "Thin",
    stage: "Order Placed",
    timeSpent: "7 min",
  },
  {
    id: 5,
    price: '250.00',
    imageUrl: "https://via.placeholder.com/50",
    name: "Supreme",
    type: "Non-Veg",
    size: "Medium",
    base: "Thick",
    stage: "Order In Making",
    timeSpent: "3 min",
  },
  {
    id: 6,
    price: '250.00',
    imageUrl: "https://via.placeholder.com/50",
    name: "Margarita",
    type: "Veg",
    size: "Small",
    base: "Thin",
    stage: "Order Ready",
    timeSpent: "12 min",
  },
  {
    id: 7,
    price: '250.00',
    imageUrl: "https://via.placeholder.com/50",
    name: "Hawaiian",
    type: "Non-Veg",
    size: "Large",
    base: "Thin",
    stage: "Order Placed",
    timeSpent: "6 min",
  },
  {
    id: 8,
    price: '250.00',
    imageUrl: "https://via.placeholder.com/50",
    name: "Four Cheese",
    type: "Veg",
    size: "Medium",
    base: "Thick",
    stage: "Order In Making",
    timeSpent: "4 min",
  },
  {
    id: 9,
    price: '250.00',
    imageUrl: "https://via.placeholder.com/50",
    name: "Meat Lovers",
    type: "Non-Veg",
    size: "Small",
    base: "Thin",
    stage: "Order Ready",
    timeSpent: "9 min",
  },
  {
    id: 10,
    price: '250.00',
    imageUrl: "https://via.placeholder.com/50",
    name: "Vegetable Supreme",
    type: "Veg",
    size: "Large",
    base: "Thin",
    stage: "Order Placed",
    timeSpent: "8 min",
  },
  {
    id: 11,
    price: '250.00',
    imageUrl: "https://via.placeholder.com/50",
    name: "Chicken Tikka",
    type: "Non-Veg",
    size: "Medium",
    base: "Thick",
    stage: "Order In Making",
    timeSpent: "6 min",
  },
  {
    id: 12,
    price: '250.00',
    imageUrl: "https://via.placeholder.com/50",
    name: "Paneer Makhani",
    type: "Veg",
    size: "Small",
    base: "Thin",
    stage: "Order Ready",
    timeSpent: "11 min",
  },
  {
    id: 13,
    price: '250.00',
    imageUrl: "https://via.placeholder.com/50",
    name: "Mushroom Delight",
    type: "Veg",
    size: "Large",
    base: "Thin",
    stage: "Order Placed",
    timeSpent: "5 min",
  },
  {
    id: 14,
    price: '250.00',
    imageUrl: "https://via.placeholder.com/50",
    name: "Bacon Bliss",
    type: "Non-Veg",
    size: "Medium",
    base: "Thick",
    stage: "Order In Making",
    timeSpent: "4 min",
  },
  {
    id: 15,
    price: '250.00',
    imageUrl: "https://via.placeholder.com/50",
    name: "Sicilian",
    type: "Veg",
    size: "Small",
    base: "Thin",
    stage: "Order Ready",
    timeSpent: "13 min",
  },
  {
    id: 16,
    price: '250.00',
    imageUrl: "https://via.placeholder.com/50",
    name: "Tandoori Chicken",
    type: "Non-Veg",
    size: "Large",
    base: "Thin",
    stage: "Order Placed",
    timeSpent: "7 min",
  },
  {
    id: 17,
    price: '250.00',
    imageUrl: "https://via.placeholder.com/50",
    name: "Greek Veggie",
    type: "Veg",
    size: "Medium",
    base: "Thick",
    stage: "Order In Making",
    timeSpent: "5 min",
  },
  {
    id: 18,
    price: '250.00',
    imageUrl: "https://via.placeholder.com/50",
    name: "Buffalo Chicken",
    type: "Non-Veg",
    size: "Small",
    base: "Thin",
    stage: "Order Ready",
    timeSpent: "10 min",
  },
  {
    id: 19,
    price: '250.00',
    imageUrl: "https://via.placeholder.com/50",
    name: "Artichoke and Spinach",
    type: "Veg",
    size: "Large",
    base: "Thin",
    stage: "Order Placed",
    timeSpent: "6 min",
  },
  {
    id: 20,
    price: '250.00',
    imageUrl: "https://via.placeholder.com/50",
    name: "Barbecue Bacon",
    type: "Non-Veg",
    size: "Medium",
    base: "Thick",
    stage: "Order In Making",
    timeSpent: "6 min",
  },
]

export default tempPizzaData
